apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: backend-failure
  labels:
    exercise: fault-injection
spec:
  destination:
    name: backend-svc
  precedence: 5
  httpFault:
    abort:
      percent: 100
      httpStatus: 500