
# This is demo cluster so give all authenticated people 'edit' rights in all namespaces
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-admins
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: User
  name: erno@polarsquad.com
- kind: User
  name: teemu.pohja@polarsquad.com