# 
# The Custom Resource Types (CRD) for Dex so it can use Kubernetes as a storage
# 
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: authcodes.dex.coreos.com
spec:
  group: dex.coreos.com
  names:
    kind: AuthCode
    listKind: AuthCodeList
    plural: authcodes
    singular: authcode
  version: v1

---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: authrequests.dex.coreos.com
spec:
  group: dex.coreos.com
  names:
    kind: AuthRequest
    listKind: AuthRequestList
    plural: authrequests
    singular: authrequest
  version: v1

---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: connectors.dex.coreos.com
spec:
  group: dex.coreos.com
  names:
    kind: Connector
    listKind: ConnectorList
    plural: connectors
    singular: connector
  version: v1

---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: oauth2clients.dex.coreos.com
spec:
  group: dex.coreos.com
  names:
    kind: OAuth2Client
    listKind: OAuth2ClientList
    plural: oauth2clients
    singular: oauth2client
  version: v1

---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: offlinesessionses.dex.coreos.com
spec:
  group: dex.coreos.com
  names:
    kind: OfflineSessions
    listKind: OfflineSessionsList
    plural: offlinesessionses
    singular: offlinesessions
  version: v1

---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: passwords.dex.coreos.com
spec:
  group: dex.coreos.com
  names:
    kind: Password
    listKind: PasswordList
    plural: passwords
    singular: password
  version: v1

---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: refreshtokens.dex.coreos.com
spec:
  group: dex.coreos.com
  names:
    kind: RefreshToken
    listKind: RefreshTokenList
    plural: refreshtokens
    singular: refreshtoken
  version: v1

---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: signingkeies.dex.coreos.com
spec:
  group: dex.coreos.com
  names:
    kind: SigningKey
    listKind: SigningKeyList
    plural: signingkeies
    singular: signingkey
  version: v1