apiVersion: apps/v1beta2
kind: ReplicaSet
metadata:
  name: kubers
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kubers
  template:
    metadata:
      labels:
        app: kubers
    spec:
      containers:
      - name: kubers
        image: luksa/kubia

